module.exports = {
    identity:'chat',
    connection:'rosie',
    autoCreatedAt:true,
    autoUpdatedAt:true,
    autoPK:true,
    migrate:'alter',
    attributes:{
        from:{
            type:'string'
        },
        to:{
            type:'string'
        },
        message:{
            type:'string'
        }
    }
};
